#!/bin/bash
dot -Tsvg woordweb_woorden.dot -o woordweb_woorden.svg
#twopi -Tsvg woordweb_woorden.dot -o woordweb_woorden.svg
#circo -Tsvg woordweb_woorden.dot -o woordweb_woorden.svg
convert woordweb_woorden.svg -rotate 90 woordweb_woorden.png
